language: node_js
services:
  - mysql
before_install:
  - mysql -u root --password="" creditsworld_test < server/loader_part.sql
install:
- nvm install node
- node -v
- cd server
- npm i -g yarn
- yarn
- npm install --save-dev jest
- npm install --save-dev @babel/plugin-transform-modules-commonjs
script:
- yarn test --coverage