sudo: required
language: node_js
services:
  - mysql
before_install:
  - sudo cp $TRAVIS_BUILD_DIR/_travis/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart
  - mysql -e "CREATE DATABASE IF NOT EXISTS creditsworld_test;"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '5648';"
  - mysql -u root --password="5648" --default-character-set=utf8 creditsworld_test < server/loader_part.sql
install:
- nvm install node
- node -v
- cd server
- npm i -g yarn
- yarn
- npm install --save-dev jest
- npm install --save-dev @babel/plugin-transform-modules-commonjs
script:
- yarn test --coverage